---
site:
  title: Jenkins Docs
  start_page: user-docs::index.adoc

content:
  sources:
    - url: ../
      # Change the branch name to the one you are working on for preview
      branches: [main]
      start_paths: [
        docs/solutions,
        docs/tutorials,
        docs/user-docs
      ]
      # developer docs are un-versioned that's why they're fetched individually
    - url: ../
      # Change the branch name to the one you are working on for preview
      branches: [main]
      start_paths: [
        docs/about,
        docs/books,
        docs/community,
        docs/dev-docs,
        docs/download,
        docs/events,
        docs/images,
        docs/project,
        docs/projects,
        docs/security,
        docs/sigs
      ]

runtime:
  cache_dir: ./.cache/antora
  fetch: true
  log:
    level: error

asciidoc:
  attributes:
    page-pagination: ''
    plugin: https://plugins.jenkins.io/
    jira: https://issues.jenkins.io/browse/
    jep: https://github.com/jenkinsci/jep/tree/master/jep/
    matrix: https://matrix.to/#/#
    email: jenkinsci-users@googlegroups.com

ui:
  bundle:
    url: ../ui/build/ui-bundle.zip
    snapshot: true
